# Generated by Django 3.2.3 on 2021-05-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=264)),
                ('Size', models.IntegerField()),
                ('Developer', models.CharField(max_length=256)),
                ('Description', models.CharField(max_length=1024)),
                ('cover_image', models.CharField(max_length=256)),
                ('Gameplay_images', models.CharField(max_length=256)),
                ('poster', models.CharField(max_length=256)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
