# Generated by Django 3.2.3 on 2021-05-19 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='price',
        ),
    ]
