# Generated by Django 3.2.3 on 2021-05-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0002_remove_game_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
