# Generated by Django 3.1.3 on 2021-06-05 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0003_game_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='Gameplay_images',
        ),
        migrations.RemoveField(
            model_name='game',
            name='poster',
        ),
        migrations.AddField(
            model_name='game',
            name='Popular',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
